### ISSUE TITLE
when i change my app theme to custom theme,it has an error:

### ISSUE THREAD

**Issue by yaochangliang159** [avast/android-styled-dialogs#129]
01-10 08:14:36.591: E/AndroidRuntime(2607): FATAL EXCEPTION: main
01-10 08:14:36.591: E/AndroidRuntime(2607): Process: com.ehetu.o2o, PID: 2607
01-10 08:14:36.591: E/AndroidRuntime(2607): android.view.InflateException: Binary XML file line #41: Error inflating class <unknown>
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at com.avast.android.dialogs.core.BaseDialogFragment$Builder.create(BaseDialogFragment.java:403)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at com.avast.android.dialogs.core.BaseDialogFragment.onCreateView(BaseDialogFragment.java:82)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1026)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1207)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1572)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:493)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.os.Handler.handleCallback(Handler.java:739)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.os.Handler.dispatchMessage(Handler.java:95)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.os.Looper.loop(Looper.java:135)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at java.lang.reflect.Method.invoke(Native Method)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at java.lang.reflect.Method.invoke(Method.java:372)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
01-10 08:14:36.591: E/AndroidRuntime(2607): Caused by: java.lang.reflect.InvocationTargetException
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at java.lang.reflect.Constructor.newInstance(Native Method)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	... 23 more
01-10 08:14:36.591: E/AndroidRuntime(2607): Caused by: java.lang.RuntimeException: Failed to resolve attribute at index 5
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.content.res.TypedArray.getColorStateList(TypedArray.java:425)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.widget.TextView.<init>(TextView.java:987)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.widget.Button.<init>(Button.java:111)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.widget.Button.<init>(Button.java:107)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	at android.widget.Button.<init>(Button.java:103)
01-10 08:14:36.591: E/AndroidRuntime(2607): 	... 26 more

i download your code ,and run it in eclipse ,it is OK, but when i copy the library code into my application,and run it,has an error,
and this is what i search on stackoverflow:
http://stackoverflow.com/questions/18602820/samsung-galaxy-holoeverywhere-resource-is-not-a-colorstatelist-color-or-path/18826126#18826126

http://stackoverflow.com/questions/28626407/android-content-res-resourcesnotfoundexception-resource-is-not-a-drawable-col

could you help me?

**Comment by yaochangliang159** [comment]
when i change my app theme like this: android:theme="@style/AppTheme",it is ok,but when i change my app theme like this: android:theme="@style/horizontal_slide",it has an error.......how to rosolve this problem??...

**Comment by yaochangliang159** [comment]
i have solved the problem ,i change the parent="android:Theme.NoTitleBar"    to   parent="AppBaseTheme",it is ok
