### ISSUE TITLE
Caused by android.os.BadParcelableException Parcelable protocol requires a Parcelable.Creator object called CREATOR on class com.tw.coffinfakecall.dialogs.util.SparseBooleanArrayParcelable com.tw.coffinfakecall.dialogs.core.BaseDialogFragment.resolveTheme

### ISSUE THREAD

**Issue by Timan86** [avast/android-styled-dialogs#144]
Caused by android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class com.**.dialogs.util.SparseBooleanArrayParcelable
       at android.os.Parcel.readParcelableCreator(Parcel.java:2549)
       at android.os.Parcel.readParcelable(Parcel.java:2471)
       at android.os.Parcel.readValue(Parcel.java:2374)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:2727)
       at android.os.BaseBundle.unparcel(BaseBundle.java:269)
       at android.os.BaseBundle.getBoolean(BaseBundle.java:694)
       at com.tw.coffinfakecall.dialogs.core.BaseDialogFragment.resolveTheme(BaseDialogFragment.java:239)
       at com.tw.coffinfakecall.dialogs.core.BaseDialogFragment.onCreateDialog(BaseDialogFragment.java:72)
       at androidx.fragment.app.DialogFragment.onGetLayoutInflater(DialogFragment.java:380)
       at androidx.fragment.app.Fragment.performGetLayoutInflater(Fragment.java:1412)

**Comment by Timan86** [comment]
my project use proguard.pro
use below code did not workong in some devices
-keep class * implements android.os.Parcelable {                         
  public static final android.os.Parcelable$Creator *;
}
-keepclassmembers class * implements android.os.Parcelable {
    public static final ** CREATOR;
}
