### ISSUE TITLE
Is there support for MultiChoice dialogs?

### ISSUE THREAD

**Issue by loeschg** [avast/android-styled-dialogs#42]
See http://developer.android.com/guide/topics/ui/dialogs.html#Checkboxes

**Comment by chenenyu** [comment]
A good library :+1:

**Comment by chenenyu** [comment]
Caused by: android.content.res.Resources$NotFoundException: Resource is not a ColorStateList (color or path): TypedValue{t=0x2/d=0x7f01009f a=3}
            at android.content.res.Resources.loadColorStateList(Resources.java:2307)
            at com.huawei.android.content.res.ResourcesEx.loadColorStateList(ResourcesEx.java:729)
            at android.content.res.TypedArray.getColorStateList(TypedArray.java:357)
            at android.widget.TextView.<init>(TextView.java:979)
            at android.widget.Button.<init>(Button.java:107)
            at android.widget.Button.<init>(Button.java:103)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:594)
            ...

What should i do? ...   :(

**Comment by destil** [comment]
We now have multi-choice dialogs, thanks to @martinpelant!
